version: "3"
services:
  nginx:
    container_name: online-monaco-editor-nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./frontend/build/:/var/www/html"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
  webapp:
    container_name: online-monaco-editor-web
    build:
      context: ./backend/
    ports:
      - "7777:8000"
    volumes:
      - "./code/:/code/"
