version: "3"
services:
  webapp:
    container_name: online-monaco-editor
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7777:80"
    volumes:
      - "./code/:/code/"
      - "./frontend/build/:/var/www/html"
      - "./default.conf:/etc/nginx/sites-available/default"
